openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jeraldlyh/HoloRPG/1.0.0
info:
  description: "List of API endpoints available"
  version: "1.0.0"
  title: HoloRPG API
  contact:
    email: jeraldssw@gmail.com
tags:
  - name: admins
    description: Secured calls for admin only
  - name: users
    description: Operations available to authenticated users
paths:
  /api/auth/social/google/:
    post:
      tags:
        - users
      summary: Login/Registration (Google Provider)
      operationId: loginGoogle
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
  /api/auth/login/:
    post:
      tags:
        - users
      summary: Login (Django Authentication)
      operationId: loginDjango
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
  /api/auth/logout/:
    post:
      tags:
        - users
      summary: Logout user
      operationId: logout
      parameters:
        - in: query
          name: refresh
          required: true
          description: Refresh token
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    default: Successfully logged out
  /api/auth/token/refresh/:
    post:
      tags:
        - users
      summary: Refresh access token
      operationId: refreshToken
      parameters:
        - in: query
          name: refresh
          required: true
          description: Refresh token
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                  access_token_expiration:
                    type: string
                    format: date-time
  /api/profile:
    get:
      tags:
        - users
      summary: Get all profiles
      operationId: getAllProfiles
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserProfile"
  /api/profile/{id}:
    get:
      tags:
        - users
      summary: Get profile by username
      operationId: getProfile
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Username
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
  /api/bounty/:
    get:
      tags:
        - users
      summary: Get list of players that are listed on the bounty list and X number of random players for users to place bounty on
      operationId: getBounty
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  bounty:
                    type: array
                    items:
                      $ref: "#/components/schemas/Bounty"
                  player:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserProfile"
    post:
      tags:
        - users
      summary: Creates a bounty
      operationId: createBounty
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: target
          required: true
          description: Player that is getting placed on the bounty list
          schema:
            type: string
        - in: query
          name: placed_by
          required: true
          description: Player that is placing the bounty
          schema:
            type: string
        - in: query
          name: value
          required: true
          description: Value of the target's bounty
          schema:
            type: integer
      responses:
        "201":
          description: CREATED
        "400":
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/SameUserError"
                  - $ref: "#/components/schemas/BountyExistError"
                  - $ref: "#/components/schemas/InsufficientHealthError"
                  - $ref: "#/components/schemas/InsufficientCurrencyError"
  /api/bounty/{id}:
    patch:
      tags:
        - users
      summary: Attacks a player
      operationId: attackPlayer
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Bounty ID
          schema:
            type: string
        - in: query
          name: attacker
          required: true
          description: Attacker's username
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  rewards:
                    type: object
                    properties:
                      target:
                        type: string
                      damage:
                        type: integer
                      currency:
                        type: integer
                      level:
                        type: integer
                      experience:
                        type: integer
                  bounty:
                    type: array
                    items:
                      $ref: "#/components/schemas/Bounty"
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsufficientHealthError"
# ---------------------------------------------------------------------------- #
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SameUserError:
      type: object
      properties:
        message:
          type: string
          default: Unable to place bounty on yourself
    BountyExistError:
      type: object
      properties:
        message:
          type: string
          default: <targetName> currently has an existing bounty
    InsufficientHealthError:
      type: object
      properties:
        message:
          type: string
          default: <targetName> is currently dead
    InsufficientCurrencyError:
      type: object
      properties:
        message:
          type: string
          default: <playerName> has insufficient currency
    Token:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        user:
          type: object
          properties:
            pk:
              type: string
            username:
              type: string
            email:
              type: string
    Character:
      type: object
      required:
        - main_class
      properties:
        main_class:
          type: string
          default: DEFAULT
          maxLength: 32
    UserProfile:
      type: object
      required:
        - username
        - email
        - password
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          maxLength: 254
        username:
          type: string
        is_staff:
          type: boolean
          default: false
        is_superuser:
          type: boolean
          default: false
        is_active:
          type: boolean
          default: false
        last_login:
          type: string
          format: date-time
        date_joined:
          type: string
          format: date-time
        has_changed_name:
          type: boolean
          default: false
        image:
          type: string
          maxLength: 100
        character:
          $ref: "#/components/schemas/Character"
        level:
          type: integer
          default: 1
        experience:
          type: integer
          default: 0
        currency:
          type: integer
          default: 1000
        reputation:
          type: integer
          default: 0
        current_health:
          type: integer
          default: 100
        max_health:
          type: integer
          default: 100
        attack:
          type: integer
          default: 1
        defence:
          type: integer
          default: 1
        status:
          type: string
          maxLength: 10
        account_age:
          type: integer
        character_class: # Check again if character is repeated
          type: string
        rank:
          type: integer
        income_accumulated:
          type: integer
          default: 0
        net_worth:
          type: integer
          default: 0
        last_collected:
          type: string
          format: date-time
        exp_required:
          type: integer
    Relationship:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 10
          enum:
            - Friend
            - Family
    UserRelationship:
      type: object
      required:
        - user_from
        - user_to
        - relationship
      properties:
        user_from:
          $ref: "#/components/schemas/UserProfile"
        user_to:
          $ref: "#/components/schemas/UserProfile"
        relationship:
          $ref: "#/components/schemas/Relationship"
    Bounty:
      type: object
      required:
        - placed_by
        - target
        - value
      properties:
        id:
          type: string
          format: uuid
        placed_by:
          type: string
        target:
          type: string
        value:
          type: integer
        placed_at:
          type: string
          format: date-time
          nullable: true
        claimed_by:
          type: string
        status:
          type: string
          maxLength: 10
          enum:
            - CLAIMED
            - UNCLAIMED
        target_health:
          type: object
          properties:
            current_health:
              type: integer
              default: 100
            max_health:
              type: integer
              default: 100
