# Generated by Django 3.2 on 2021-06-01 15:47

import api.room.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dungeon_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.dungeon')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(blank=True, default=api.room.utils.generate_unique_code, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started')], default='WAITING', editable=False, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monster_attack', models.IntegerField(blank=True, editable=False)),
                ('monster_defence', models.IntegerField(blank=True, editable=False)),
                ('monster_current_health', models.IntegerField(blank=True, editable=False)),
                ('monster_max_health', models.IntegerField(blank=True, editable=False)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.dungeon')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_host', to='user.userprofile', to_field='user_id')),
                ('monster', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='room.monster')),
                ('player_four', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p4', to='user.userprofile', to_field='user_id')),
                ('player_three', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p3', to='user.userprofile', to_field='user_id')),
                ('player_two', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p2', to='user.userprofile', to_field='user_id')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monster',
            constraint=models.UniqueConstraint(fields=('name', 'dungeon_name'), name='unique_monster'),
        ),
    ]
