# Generated by Django 3.2 on 2021-05-17 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.CharField(choices=[('Warrior', 'Warrior'), ('Archer', 'Archer'), ('Magician', 'Magician'), ('Rogue', 'Rogue'), ('Default', 'Beginner')], default='Default', max_length=32)),
                ('sub_class', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('main_class', 'sub_class')},
            },
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('current_health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('dungeon_status', models.CharField(max_length=32)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.character')),
                ('dungeon_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon', to_field='level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('accuracy', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.character')),
            ],
            options={
                'unique_together': {('character', 'name')},
            },
        ),
    ]
