# Generated by Django 3.2 on 2021-05-26 07:11

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.CharField(choices=[('Warrior', 'Warrior'), ('Archer', 'Archer'), ('Magician', 'Magician'), ('Rogue', 'Rogue'), ('Default', 'Beginner')], default='Default', max_length=32)),
                ('sub_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dungeon_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('name', models.CharField(choices=[('FRIEND', 'Friend'), ('FAMILY', 'Family')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('current_health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.relationship')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelationship_from', to='api.userprofile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelationship_to', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(blank=True, default=api.models.generate_unique_code, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started')], default='WAITING', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monster_attack', models.IntegerField(blank=True)),
                ('monster_defence', models.IntegerField(blank=True)),
                ('monster_current_health', models.IntegerField(blank=True)),
                ('monster_max_health', models.IntegerField(blank=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_host', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('monster', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.monster')),
                ('player_four', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p4', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('player_three', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p3', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('player_two', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p2', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('main_class', 'sub_class'), name='unique_character'),
        ),
        migrations.AddConstraint(
            model_name='userrelationship',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_relationship'),
        ),
        migrations.AddConstraint(
            model_name='monster',
            constraint=models.UniqueConstraint(fields=('name', 'dungeon_name'), name='unique_monster'),
        ),
    ]
