# Generated by Django 3.2 on 2021-05-24 12:35

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(blank=True, default=api.models.generate_unique_code, max_length=6, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monster_attack', models.IntegerField(blank=True)),
                ('monster_defence', models.IntegerField(blank=True)),
                ('monster_current_health', models.IntegerField(blank=True)),
                ('monster_max_health', models.IntegerField(blank=True)),
                ('dungeon_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_host', to='api.userprofile')),
                ('monster_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.monster')),
                ('player_four', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p4', to='api.userprofile')),
                ('player_three', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p3', to='api.userprofile')),
                ('player_two', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p2', to='api.userprofile')),
            ],
        ),
    ]
