# Generated by Django 3.2 on 2021-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210526_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
