# Generated by Django 3.2 on 2021-05-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='dungeon_name',
            new_name='dungeon',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='monster_name',
            new_name='monster',
        ),
    ]
