# Generated by Django 3.2 on 2021-05-25 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210525_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=6, primary_key=True, serialize=False),
        ),
    ]
