# Generated by Django 3.2 on 2021-05-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.PositiveSmallIntegerField(choices=[(1, 'Warrior'), (2, 'Archer'), (3, 'Magician'), (4, 'Rogue'), (0, 'NONE')], default=0)),
                ('sub_class', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('main_class', 'sub_class')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('accuracy', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.character')),
            ],
            options={
                'unique_together': {('character', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='sub_class',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.character'),
        ),
    ]
