# Generated by Django 3.2 on 2021-05-15 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210514_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('current_health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('dungeon_status', models.CharField(max_length=32)),
                ('character', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.character')),
                ('dungeon_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon', to_field='level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
