# Generated by Django 3.2 on 2021-05-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210515_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='main_class',
            field=models.CharField(choices=[('Warrior', 'Warrior'), ('Archer', 'Archer'), ('Magician', 'Magician'), ('Rogue', 'Rogue'), ('Default', 'Beginner')], default='Default', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.character'),
        ),
    ]
