# Generated by Django 3.2 on 2021-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started')], default='WAITING', max_length=7),
        ),
    ]
