# Generated by Django 3.2 on 2021-05-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dungeon_name',
        ),
    ]
