# Generated by Django 3.2 on 2021-05-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.CharField(choices=[('Warrior', 'Warrior'), ('Archer', 'Archer'), ('Magician', 'Magician'), ('Rogue', 'Rogue'), ('Default', 'Beginner')], default='Default', max_length=32)),
                ('sub_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(default='https://svgshare.com/i/Xd6.svg', max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('current_health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dungeon_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon')),
            ],
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('main_class', 'sub_class'), name='unique_character'),
        ),
        migrations.AddConstraint(
            model_name='monster',
            constraint=models.UniqueConstraint(fields=('name', 'dungeon_name'), name='unique_monster'),
        ),
    ]
