# Generated by Django 3.2 on 2021-05-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='monster',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.monster'),
        ),
        migrations.AlterField(
            model_name='room',
            name='monster_attack',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='monster_current_health',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='monster_defence',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='monster_max_health',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started')], default='WAITING', editable=False, max_length=7),
        ),
    ]
