# Generated by Django 3.2 on 2021-05-28 12:46

import api.formulas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('name', models.CharField(choices=[('FRIEND', 'Friend'), ('FAMILY', 'Family')], max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.relationship')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='api.userprofile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('accuracy', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(blank=True, default=api.formulas.models.generate_unique_code, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started')], default='WAITING', editable=False, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monster_attack', models.IntegerField(blank=True, editable=False)),
                ('monster_defence', models.IntegerField(blank=True, editable=False)),
                ('monster_current_health', models.IntegerField(blank=True, editable=False)),
                ('monster_max_health', models.IntegerField(blank=True, editable=False)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dungeon')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_host', to='api.userprofile', to_field='user_id')),
                ('monster', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.monster')),
                ('player_four', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p4', to='api.userprofile', to_field='user_id')),
                ('player_three', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p3', to='api.userprofile', to_field='user_id')),
                ('player_two', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_p2', to='api.userprofile', to_field='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_placed_by', to='api.userprofile', to_field='user_id')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_target', to='api.userprofile', to_field='user_id')),
                ('status', models.CharField(blank=True, default='UNCLAIMED', editable=False, max_length=10))
            ],
        ),
        migrations.AddConstraint(
            model_name='userrelationship',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_relationship'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('character', 'name'), name='unique_skill'),
        ),
        migrations.AddConstraint(
            model_name='bounty',
            constraint=models.UniqueConstraint(fields=('placed_by', 'target'), name='unique_bounty'),
        ),
    ]
