# Generated by Django 3.2 on 2021-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210528_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='status',
            field=models.CharField(blank=True, default='UNCLAIMED', editable=False, max_length=10),
        ),
    ]
