# Generated by Django 3.2 on 2021-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='https://svgshare.com/i/Xd6.svg', max_length=100),
        ),
    ]
