# Generated by Django 3.2 on 2021-07-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=3)),
                ('shares', models.IntegerField()),
                ('type', models.CharField(choices=[('VOLATILE', 'Volatile'), ('PASSIVE', 'Passive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stock')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userstock',
            constraint=models.UniqueConstraint(fields=('placed_at', 'user'), name='unique_userstock'),
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('date', 'company_name'), name='unique_stockprice'),
        ),
    ]
