# Generated by Django 3.2 on 2021-06-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210618_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprice',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='close',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='open',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='volume',
        ),
    ]
