# Generated by Django 3.2 on 2021-06-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210619_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
