# Generated by Django 3.2 on 2021-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='defence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
