# Generated by Django 3.2 on 2021-06-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210625_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='claimed_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_by', to='user.userprofile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_by', to='user.userprofile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='user.userprofile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='user.userprofile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='user.userprofile', to_field='user_id'),
        ),
    ]
