# Generated by Django 3.2 on 2021-06-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_bounty_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='income_collected',
        ),
    ]
