# Generated by Django 3.2 on 2021-06-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210603_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='claimed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
