# Generated by Django 3.2 on 2021-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_bounty_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='claimed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
