# Generated by Django 3.2 on 2021-06-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bounty_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='claimed_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_by', to='user.userprofile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_by', to='user.userprofile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='user.userprofile', to_field='user_id'),
        ),
    ]
