# Generated by Django 3.2 on 2021-06-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210625_1406'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', to_field='user_id'),
        ),
    ]
