import math
import random
from collections import OrderedDict
from typing import List, Tuple
from django.db.models.expressions import F
from datetime import datetime

from .models import Bounty, UserProfile, UserRelationship
from .serializers import BountySerializer
from .exceptions import BountyExistError, SameUserError, InsufficientCurrencyError, InsufficientHealthError
from .selectors import get_bounties_by_status, get_bounties_by_target_status, get_bounty_by_id, get_user_by_username


def exp_required(level: int) -> int:
    """
        Current formula: (8 * Level^3) / 4
    """
    BASE_EXP = 8
    return (BASE_EXP * (level ** 3)) / 4


def damage_dealt(player: UserProfile, target: UserProfile) -> int:
    """
        Damage =  Attack^2 / (Attack + Defence)
    """
    damage = math.floor(player.attack ** 2 / (player.attack / player.defence))

    if target.current_health - damage > 0:
        target.current_health = F("current_health") - damage
    else:
        target.current_health = 0

    target.save()
    return damage


def get_user_net_worth(username: str) -> int:
    """
        User net worth is computed based on total amount of income generated by entities * 3

        Net worth = 3 * (Total income generated by entities)
    """
    from ..entity.selectors import get_user_entities_by_username

    player_entities = get_user_entities_by_username(username)

    net_worth = 0
    for entity in player_entities:
        net_worth += entity.entity.income * entity.quantity

    return net_worth * 3


def exp_gained(player: UserProfile, target: UserProfile) -> int:
    """
        Exp Gain = Level^2 +- 15
    """

    upper = (player + target) * 5
    buffer = random.randint(0, upper)
    experience = (target.level ** 2) * 4 + buffer
    player.experience = F("experience") + experience
    player.save()

    return experience


def plunder(player: UserProfile, target: UserProfile) -> int:
    """
        Target loses 5% of currency when attacked by player
    """

    currency = math.floor(5 * (target.currency / 100))
    add_player_currency(player, currency)
    deduct_player_currency(target, currency)

    return currency


def attack_target(player: UserProfile, target: UserProfile) -> Tuple[int, int, int]:
    """
        Raises InsufficientHealthError if target is already dead
        Returns the damage, currency, exp to be rendered on frontend
    """

    if target.current_health == 0:
        raise InsufficientHealthError

    damage = damage_dealt(player, target)
    experience = exp_gained(player, target)
    currency = plunder(player, target)

    return damage, currency, experience


def claim_bounty(player: UserProfile, bounty: Bounty) -> None:
    bounty.status = "CLAIMED"
    bounty.claimed_by = player
    bounty.claimed_at = datetime.now()
    bounty.save()

    add_player_currency(player, bounty.value)


def get_unclaimed_bounties() -> List[dict]:
    bounty_queryset = get_bounties_by_status("UNCLAIMED")
    bounty_serializer = BountySerializer(bounty_queryset, many=True)
    result = [dict(OrderedDict(bounty)) for bounty in bounty_serializer.data]
    return result


def add_player_currency(player: UserProfile, value) -> None:
    player.currency = F("currency") + value
    player.save()


def deduct_player_currency(player: UserProfile, value) -> None:
    player.currency = F("currency") - value
    player.save()


def attack_player_on_bounty(player_name: str, bounty_id: str) -> Tuple[int, int, int, str]:
    """
        Raises InsufficientHealthError if target is already dead prior to attack
        Returns damage dealt in battle and target profile to be rendered on frontend
    """

    player = get_user_by_username(player_name)
    bounty = get_bounty_by_id(bounty_id)

    target = bounty.target

    if target.current_health == 0:
        raise InsufficientHealthError
    
    damage, currency, exp = attack_target(player, target)
    if target.current_health == 0:
        claim_bounty(player, bounty)
    
    return damage, currency, exp, target.username


def create_bounty(serializer_data: OrderedDict) -> None:
    """
        Raises SameUserError if player places bounty on themselves
        Raises BountyExistError if an existing bounty on the target exists
        Raises InsufficientHealthError if target is already dead
        Raises InsufficientCurrencyError if player does not have enough currency
    """

    data = list(serializer_data.items())

    player = data[1][1]
    target = data[2][1]
    bounty_value = data[0][1]

    if player.username == target.username:
        raise SameUserError
    
    if get_bounties_by_target_status(target.username, "UNCLAIMED").count() != 0:
        raise BountyExistError
    
    if target.current_health == 0:
        raise InsufficientHealthError
    
    if player.currency < bounty_value:
        raise InsufficientCurrencyError
    
    deduct_player_currency(player, bounty_value)
    Bounty.objects.create(**serializer_data)


def create_user_relationship(serializer_data: OrderedDict) -> None:
    """
        Raises SameUserError if player tries to befriend themselves
    """
    data = list(serializer_data.items())
    user_from = data[0][1]
    user_to = data[1][1]

    if user_from.username == user_to.username:
        raise SameUserError

    UserRelationship.objects.create(**serializer_data)