// PROFILE ACTIONS
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL"


// ACCOUNT ACTIONS
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

// ERROR ACTIONS
export const SHOW_ERROR = "SHOW_ERROR"
export const HIDE_ERROR = "HIDE_ERROR"
export const RESET_ERROR = "RESET_ERROR"